---
- name: Install nginx
  apt: name=nginx state=latest update_cache=true

- name: Remove default nginx config
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: configuring nginx
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: adding default proxy behaviour
  copy: src=proxy.conf dest=/etc/nginx/sites-available/proxy.conf

- name: adding entry for OpenVidu requests
  template:
    src: templates/kms-ov.conf.j2
    dest: /etc/nginx/sites-enabled/kms-ov
  notify: restart nginx
