---
- name: adding script to set everything up after shutdown
  template:
    src: after-shutdown.sh.j2
    dest: /usr/local/bin/after-shutdown.sh
    mode: u+rwx
  when: 
    - whichcert == "selfsigned"
    - reverse_proxy_enabled == "true"

- name: enabling that script at boot time
  copy:
    src: rc.local
    dest: /etc
    mode: 0755
  when: 
    - whichcert == "selfsigned"
    - reverse_proxy_enabled == "true"

